### PR TITLE
added new setting NOCUSTOM

### PR DESCRIPTION
**Pull request by mojoaxel**
This makes it possible to deactivate the custom amount input section.

### CODE REVIEW

**Comment by shesek** [comment]
Implemented in e5e78c8148d43938eec0cafe05137246717e984c with some slight changes. Thanks for the contribution @mojoaxel!

**Comment by mojoaxel** [comment]
@shesek Thanks, but I would have prefered it If you would have not just copied my contributions but merged them with your changes. You as a maintainer are able to directly change or update pull-requests. This way the original contributor is recognized e.g. in a `blame` tool or in githubs `contributors` tab. It's not a problem but there is a better way to handle things like this, next time :wink:

**Comment by shesek** [comment]
Sorry, I wasn't really aware that was possible. How does that work? Would github let me commit changes to the branch under your `mojoaxel/nanopos-pinball` repo?

Will definitely take this into consideration next time, thanks for bringing this up.

**Comment by mojoaxel** [comment]
>  How does that work?

1. You could make review comments and by this ask the contributor to change something or add do some things differently. The original contributor than can just push to the same branch (or use `--amend`).
2. Repository maintainer also [can make changes to the fork-branch](https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/)  if the [user allows this](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/).

_I'm happy to help!_

**Pull request closed without merging**
