### PR TITLE
Dockerfile - Use ./dist/cli.js 

### PR DESCRIPTION
**Pull request by ch4ot1c**
Very simple Dockerfile, inspired by @blackrat 's changes, but adjusted per suggestions (#6). `docker-compose` would certainly be the next step.

### CODE REVIEW

**Comment by ch4ot1c** [comment]
Additionally, I've made some bash code to get the components up and running on DigitalOcean, with Docker.

https://github.com/ch4ot1c/lemonade-stand-lightning

Feel free to take as-needed from this code.

Note - one of the major things I encountered was that 'localhost' doesn't work but '0.0.0.0' does as the `--host` option of nanopos. Also, the block height increases (everything begins syncing), but eventually crashes per my comment in https://github.com/ElementsProject/lightning/issues/855.

Thank you all!

**Comment by shesek** [comment]
Hi @ch4ot1c, thanks for the contribution! Looks great. Could you please squash this to a single commit?

Also, regarding the host, I think it should be set to `0.0.0.0` by default in the docker environment. This can be achieved by adding `ENV HOST=0.0.0.0` to the `Dockerfile`.

**Comment by ch4ot1c** [comment]
squash again or is this ok?

**Comment by shesek** [comment]
Yes, please squash :)

**Pull request merged**
